/* MiniJavaParser.java */
/* Generated By:JavaCC: Do not edit this line. MiniJavaParser.java */
package Parse;
import java.util.LinkedList;
public class MiniJavaParser implements MiniJavaParserConstants {

  static final public Absyn.Program Goal() throws ParseException {LinkedList<Absyn.ClassDecl> classes = new LinkedList<Absyn.ClassDecl>();
    Absyn.ClassDecl c;
    c = MainClassDeclaration();
classes.add(c);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CLASS:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      c = ClassOrThreadDeclaration();
classes.add(c);
    }
    jj_consume_token(0);
{if ("" != null) return new Absyn.Program(classes);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.ClassDecl MainClassDeclaration() throws ParseException {Token name, arg; Absyn.VarDecl var; Absyn.Stmt stmt;
    LinkedList<Absyn.Formal> params=new LinkedList<Absyn.Formal>();
    LinkedList<Absyn.VarDecl> locals=new LinkedList<Absyn.VarDecl>();
    LinkedList<Absyn.Stmt> stmts=new LinkedList<Absyn.Stmt>();
    LinkedList<Absyn.MethodDecl> methods=new LinkedList<Absyn.MethodDecl>();
    jj_consume_token(CLASS);
    name = jj_consume_token(ID);
    jj_consume_token(LBRACE);
    jj_consume_token(PUBLIC);
    jj_consume_token(STATIC);
    jj_consume_token(VOID);
    jj_consume_token(MAIN);
    jj_consume_token(LPAREN);
    jj_consume_token(STRING_TYPE);
    jj_consume_token(LBRACKET);
    jj_consume_token(RBRACKET);
    arg = jj_consume_token(ID);
    jj_consume_token(RPAREN);
params.add(new Absyn.Formal(new Absyn.ArrayType(new Absyn.IdentifierType("String")),arg.image));
    jj_consume_token(LBRACE);
    label_2:
    while (true) {
      if (jj_2_1(2147483647)) {
        ;
      } else {
        break label_2;
      }
      var = VarDeclaration();
locals.add(var);
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case XINU:
      case IF:
      case WHILE:
      case NEW:
      case TRUE:
      case FALSE:
      case THIS:
      case NULL:
      case MINUS:
      case NOT:
      case LBRACE:
      case LPAREN:
      case INT:
      case STRING:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_3;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(RBRACE);
    jj_consume_token(RBRACE);
methods.add(new Absyn.MethodDecl(null,false,"main",params,locals,stmts,new Absyn.IntegerLiteral(0)));
        {if ("" != null) return new Absyn.ClassDecl(name.image,null,new LinkedList<Absyn.VarDecl>(),methods);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.ClassDecl ClassOrThreadDeclaration() throws ParseException {Token name, parent=null; boolean thread=false; Absyn.VarDecl field; Absyn.MethodDecl method;
    LinkedList<Absyn.VarDecl> fields=new LinkedList<Absyn.VarDecl>();
    LinkedList<Absyn.MethodDecl> methods=new LinkedList<Absyn.MethodDecl>();
    jj_consume_token(CLASS);
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EXTENDS:{
      jj_consume_token(EXTENDS);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ID:{
        parent = jj_consume_token(ID);
        break;
        }
      case THREAD:{
        jj_consume_token(THREAD);
thread=true;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    jj_consume_token(LBRACE);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PUBLIC:
      case BOOLEAN:
      case INT_TYPE:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      if (jj_2_2(2147483647)) {
        method = VoidDeclaration();
if(!thread) {if (true) throw new ParseException("void methods are only allowed in Thread classes");} methods.add(method);
      } else if (jj_2_3(2147483647)) {
        method = MethodDeclaration();
methods.add(method);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case BOOLEAN:
        case INT_TYPE:
        case ID:{
          field = FieldDeclaration();
fields.add(field);
          break;
          }
        default:
          jj_la1[5] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    jj_consume_token(RBRACE);
if(thread) {if ("" != null) return new Absyn.ThreadDecl(name.image,fields,methods);}
        {if ("" != null) return new Absyn.ClassDecl(name.image,parent==null?null:parent.image,fields,methods);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.VarDecl FieldDeclaration() throws ParseException {Absyn.Type type; Token name;
    type = Type();
    name = jj_consume_token(ID);
    jj_consume_token(SEMICOLON);
{if ("" != null) return new Absyn.VarDecl(type,name.image,null);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.VarDecl VarDeclaration() throws ParseException {Absyn.Type type; Token name; Absyn.Expr init=null;
    type = Type();
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      jj_consume_token(ASSIGN);
      init = Expression();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    jj_consume_token(SEMICOLON);
{if ("" != null) return new Absyn.VarDecl(type,name.image,init);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Type Type() throws ParseException {Absyn.Type type;
    type = BaseType();
    label_5:
    while (true) {
      if (jj_2_4(2)) {
        ;
      } else {
        break label_5;
      }
      jj_consume_token(LBRACKET);
      jj_consume_token(RBRACKET);
type=new Absyn.ArrayType(type);
    }
{if ("" != null) return type;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Type BaseType() throws ParseException {Token name;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BOOLEAN:{
      jj_consume_token(BOOLEAN);
{if ("" != null) return new Absyn.BooleanType();}
      break;
      }
    case INT_TYPE:{
      jj_consume_token(INT_TYPE);
{if ("" != null) return new Absyn.IntegerType();}
      break;
      }
    case ID:{
      name = jj_consume_token(ID);
{if ("" != null) return new Absyn.IdentifierType(name.image);}
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.MethodDecl MethodDeclaration() throws ParseException {boolean synced=false; Absyn.Type result,pt; Token name,pn; Absyn.VarDecl var; Absyn.Stmt stmt; Absyn.Expr value;
    LinkedList<Absyn.Formal> params=new LinkedList<Absyn.Formal>();
    LinkedList<Absyn.VarDecl> locals=new LinkedList<Absyn.VarDecl>();
    LinkedList<Absyn.Stmt> stmts=new LinkedList<Absyn.Stmt>();
    jj_consume_token(PUBLIC);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SYNCHRONIZED:{
      jj_consume_token(SYNCHRONIZED);
synced=true;
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    result = Type();
    name = jj_consume_token(ID);
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BOOLEAN:
    case INT_TYPE:
    case ID:{
      pt = Type();
      pn = jj_consume_token(ID);
params.add(new Absyn.Formal(pt,pn.image));
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[9] = jj_gen;
          break label_6;
        }
        jj_consume_token(COMMA);
        pt = Type();
        pn = jj_consume_token(ID);
params.add(new Absyn.Formal(pt,pn.image));
      }
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    label_7:
    while (true) {
      if (jj_2_5(2147483647)) {
        ;
      } else {
        break label_7;
      }
      var = VarDeclaration();
locals.add(var);
    }
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case XINU:
      case IF:
      case WHILE:
      case NEW:
      case TRUE:
      case FALSE:
      case THIS:
      case NULL:
      case MINUS:
      case NOT:
      case LBRACE:
      case LPAREN:
      case INT:
      case STRING:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_8;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(RETURN);
    value = Expression();
    jj_consume_token(SEMICOLON);
    jj_consume_token(RBRACE);
{if ("" != null) return new Absyn.MethodDecl(result,synced,name.image,params,locals,stmts,value);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.VoidDecl VoidDeclaration() throws ParseException {Token name; Absyn.VarDecl var; Absyn.Stmt stmt;
    LinkedList<Absyn.VarDecl> locals=new LinkedList<Absyn.VarDecl>();
    LinkedList<Absyn.Stmt> stmts=new LinkedList<Absyn.Stmt>();
    jj_consume_token(PUBLIC);
    jj_consume_token(VOID);
    name = jj_consume_token(ID);
    jj_consume_token(LPAREN);
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    label_9:
    while (true) {
      if (jj_2_6(2147483647)) {
        ;
      } else {
        break label_9;
      }
      var = VarDeclaration();
locals.add(var);
    }
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case XINU:
      case IF:
      case WHILE:
      case NEW:
      case TRUE:
      case FALSE:
      case THIS:
      case NULL:
      case MINUS:
      case NOT:
      case LBRACE:
      case LPAREN:
      case INT:
      case STRING:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_10;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(RBRACE);
{if ("" != null) return new Absyn.VoidDecl(name.image,locals,stmts);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Stmt Statement() throws ParseException {Absyn.Stmt stmt;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACE:{
      stmt = BlockStatement();
{if ("" != null) return stmt;}
      break;
      }
    case IF:{
      stmt = IfStatement();
{if ("" != null) return stmt;}
      break;
      }
    case WHILE:{
      stmt = WhileStatement();
{if ("" != null) return stmt;}
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      if (jj_2_7(2147483647)) {
        stmt = XinuCallStatement();
{if ("" != null) return stmt;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case XINU:
        case NEW:
        case TRUE:
        case FALSE:
        case THIS:
        case NULL:
        case MINUS:
        case NOT:
        case LPAREN:
        case INT:
        case STRING:
        case ID:{
          stmt = AssignmentStatement();
{if ("" != null) return stmt;}
          break;
          }
        default:
          jj_la1[14] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.BlockStmt BlockStatement() throws ParseException {Absyn.Stmt s; LinkedList<Absyn.Stmt> list=new LinkedList<Absyn.Stmt>();
    jj_consume_token(LBRACE);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case XINU:
      case IF:
      case WHILE:
      case NEW:
      case TRUE:
      case FALSE:
      case THIS:
      case NULL:
      case MINUS:
      case NOT:
      case LBRACE:
      case LPAREN:
      case INT:
      case STRING:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        break label_11;
      }
      s = Statement();
list.add(s);
    }
    jj_consume_token(RBRACE);
{if ("" != null) return new Absyn.BlockStmt(list);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.IfStmt IfStatement() throws ParseException {Absyn.Expr test; Absyn.Stmt yes,no=null;
    jj_consume_token(IF);
    jj_consume_token(LPAREN);
    test = Expression();
    jj_consume_token(RPAREN);
    yes = Statement();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      no = Statement();
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
{if ("" != null) return new Absyn.IfStmt(test,yes,no);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.WhileStmt WhileStatement() throws ParseException {Absyn.Expr test; Absyn.Stmt body;
    jj_consume_token(WHILE);
    jj_consume_token(LPAREN);
    test = Expression();
    jj_consume_token(RPAREN);
    body = Statement();
{if ("" != null) return new Absyn.WhileStmt(test,body);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.XinuCallStmt XinuCallStatement() throws ParseException {Token method; LinkedList<Absyn.Expr> args;
    jj_consume_token(XINU);
    jj_consume_token(DOT);
    method = jj_consume_token(ID);
    jj_consume_token(LPAREN);
    args = Arguments();
    jj_consume_token(RPAREN);
    jj_consume_token(SEMICOLON);
{if ("" != null) return new Absyn.XinuCallStmt(method.image,args);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.AssignStmt AssignmentStatement() throws ParseException {Absyn.Expr lhs,rhs;
    lhs = Expression();
    jj_consume_token(ASSIGN);
    rhs = Expression();
    jj_consume_token(SEMICOLON);
if(!(lhs instanceof Absyn.AssignableExpr)) {if (true) throw new ParseException("left side of assignment is not assignable");}
        {if ("" != null) return new Absyn.AssignStmt((Absyn.AssignableExpr)lhs,rhs);}
    throw new Error("Missing return statement in function");
}

  static final public LinkedList<Absyn.Expr> Arguments() throws ParseException {LinkedList<Absyn.Expr> args=new LinkedList<Absyn.Expr>(); Absyn.Expr e;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case XINU:
    case NEW:
    case TRUE:
    case FALSE:
    case THIS:
    case NULL:
    case MINUS:
    case NOT:
    case LPAREN:
    case INT:
    case STRING:
    case ID:{
      e = Expression();
args.add(e);
      label_12:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[17] = jj_gen;
          break label_12;
        }
        jj_consume_token(COMMA);
        e = Expression();
args.add(e);
      }
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      ;
    }
{if ("" != null) return args;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr Expression() throws ParseException {Absyn.Expr e;
    e = OrExpression();
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr OrExpression() throws ParseException {Absyn.Expr a,b;
    a = AndExpression();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        break label_13;
      }
      jj_consume_token(OR);
      b = AndExpression();
a=new Absyn.OrExpr(a,b);
    }
{if ("" != null) return a;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr AndExpression() throws ParseException {Absyn.Expr a,b;
    a = EqualityExpression();
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        break label_14;
      }
      jj_consume_token(AND);
      b = EqualityExpression();
a=new Absyn.AndExpr(a,b);
    }
{if ("" != null) return a;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr EqualityExpression() throws ParseException {Absyn.Expr a,b;
    a = RelationalExpression();
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ:
      case NE:{
        ;
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        break label_15;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ:{
        jj_consume_token(EQ);
        b = RelationalExpression();
a=new Absyn.EqualExpr(a,b);
        break;
        }
      case NE:{
        jj_consume_token(NE);
        b = RelationalExpression();
a=new Absyn.NotEqExpr(a,b);
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return a;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr RelationalExpression() throws ParseException {Absyn.Expr a,b;
    a = AdditiveExpression();
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case GT:
      case LT:{
        ;
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        break label_16;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LT:{
        jj_consume_token(LT);
        b = AdditiveExpression();
a=new Absyn.LesserExpr(a,b);
        break;
        }
      case GT:{
        jj_consume_token(GT);
        b = AdditiveExpression();
a=new Absyn.GreaterExpr(a,b);
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return a;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr AdditiveExpression() throws ParseException {Absyn.Expr a,b;
    a = MultiplicativeExpression();
    label_17:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_17;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        jj_consume_token(PLUS);
        b = MultiplicativeExpression();
a=new Absyn.AddExpr(a,b);
        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
        b = MultiplicativeExpression();
a=new Absyn.SubExpr(a,b);
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return a;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr MultiplicativeExpression() throws ParseException {Absyn.Expr a,b;
    a = UnaryExpression();
    label_18:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIMES:
      case DIVIDE:{
        ;
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        break label_18;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIMES:{
        jj_consume_token(TIMES);
        b = UnaryExpression();
a=new Absyn.MulExpr(a,b);
        break;
        }
      case DIVIDE:{
        jj_consume_token(DIVIDE);
        b = UnaryExpression();
a=new Absyn.DivExpr(a,b);
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return a;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr UnaryExpression() throws ParseException {Absyn.Expr e;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MINUS:{
      jj_consume_token(MINUS);
      e = UnaryExpression();
{if ("" != null) return new Absyn.NegExpr(e);}
      break;
      }
    case NOT:{
      jj_consume_token(NOT);
      e = UnaryExpression();
{if ("" != null) return new Absyn.NotExpr(e);}
      break;
      }
    case XINU:
    case NEW:
    case TRUE:
    case FALSE:
    case THIS:
    case NULL:
    case LPAREN:
    case INT:
    case STRING:
    case ID:{
      e = PostfixExpression();
{if ("" != null) return e;}
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr PostfixExpression() throws ParseException {Absyn.Expr e,index; Token member; LinkedList<Absyn.Expr> args;
    e = PrimaryExpression();
    label_19:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOT:
      case LBRACKET:{
        ;
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        break label_19;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LBRACKET:{
        jj_consume_token(LBRACKET);
        index = Expression();
        jj_consume_token(RBRACKET);
e=new Absyn.ArrayExpr(e,index);
        break;
        }
      case DOT:{
        jj_consume_token(DOT);
        member = jj_consume_token(ID);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LPAREN:{
          jj_consume_token(LPAREN);
          args = Arguments();
          jj_consume_token(RPAREN);
e=new Absyn.CallExpr(e,member.image,args);
          break;
          }
        default:
          jj_la1[31] = jj_gen;
e=new Absyn.FieldExpr(e,member.image);
        }
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr PrimaryExpression() throws ParseException {Token t; Absyn.Expr e,size; Absyn.Type type; LinkedList<Absyn.Expr> args,dims;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      t = jj_consume_token(ID);
{if ("" != null) return new Absyn.IdentifierExpr(t.image);}
      break;
      }
    case INT:{
      t = jj_consume_token(INT);
{if ("" != null) return new Absyn.IntegerLiteral(Integer.valueOf(t.image));}
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
{if ("" != null) return new Absyn.StringLiteral(t.image);}
      break;
      }
    case TRUE:{
      jj_consume_token(TRUE);
{if ("" != null) return new Absyn.TrueExpr();}
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
{if ("" != null) return new Absyn.FalseExpr();}
      break;
      }
    case THIS:{
      jj_consume_token(THIS);
{if ("" != null) return new Absyn.ThisExpr();}
      break;
      }
    case NULL:{
      jj_consume_token(NULL);
{if ("" != null) return new Absyn.NullExpr();}
      break;
      }
    case LPAREN:{
      jj_consume_token(LPAREN);
      e = Expression();
      jj_consume_token(RPAREN);
{if ("" != null) return e;}
      break;
      }
    case XINU:{
      jj_consume_token(XINU);
      jj_consume_token(DOT);
      t = jj_consume_token(ID);
      jj_consume_token(LPAREN);
      args = Arguments();
      jj_consume_token(RPAREN);
{if ("" != null) return new Absyn.XinuCallExpr(t.image,args);}
      break;
      }
    case NEW:{
      jj_consume_token(NEW);
      type = Type();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:{
        jj_consume_token(LPAREN);
        jj_consume_token(RPAREN);
{if ("" != null) return new Absyn.NewObjectExpr(type);}
        break;
        }
      case LBRACKET:{
        jj_consume_token(LBRACKET);
        size = Expression();
        jj_consume_token(RBRACKET);
dims=new LinkedList<Absyn.Expr>();dims.add(size);
        label_20:
        while (true) {
          if (jj_2_8(2)) {
            ;
          } else {
            break label_20;
          }
          jj_consume_token(LBRACKET);
          jj_consume_token(RBRACKET);
dims.add(null);
        }
{if ("" != null) return new Absyn.NewArrayExpr(type,dims);}
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_3R_UnaryExpression_182_7_49()
 {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_UnaryExpression_181_7_44()) return true;
    return false;
  }

  static private boolean jj_3R_UnaryExpression_181_7_48()
 {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_UnaryExpression_181_7_44()) return true;
    return false;
  }

  static private boolean jj_3R_UnaryExpression_181_7_44()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_UnaryExpression_181_7_48()) {
    jj_scanpos = xsp;
    if (jj_3R_UnaryExpression_182_7_49()) {
    jj_scanpos = xsp;
    if (jj_3R_UnaryExpression_183_7_50()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_VarDeclaration_100_5_21()) return true;
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpression_178_5_40()
 {
    if (jj_3R_UnaryExpression_181_7_44()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MultiplicativeExpression_178_26_45()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_AdditiveExpression_175_5_36()
 {
    if (jj_3R_MultiplicativeExpression_178_5_40()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AdditiveExpression_175_35_41()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_RelationalExpression_172_5_34()
 {
    if (jj_3R_AdditiveExpression_175_5_36()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_RelationalExpression_172_29_37()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_AdditiveExpression_175_97_47()
 {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_MultiplicativeExpression_178_5_40()) return true;
    return false;
  }

  static private boolean jj_3R_EqualityExpression_169_5_32()
 {
    if (jj_3R_RelationalExpression_172_5_34()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_EqualityExpression_169_31_35()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Arguments_163_6_73()
 {
    if (jj_3R_Expression_165_47_25()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Arguments_163_36_74()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Arguments_163_5_68()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Arguments_163_6_73()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_EqualityExpression_169_92_39()
 {
    if (jj_scan_token(NE)) return true;
    if (jj_3R_RelationalExpression_172_5_34()) return true;
    return false;
  }

  static private boolean jj_3R_RelationalExpression_172_88_43()
 {
    if (jj_scan_token(GT)) return true;
    if (jj_3R_AdditiveExpression_175_5_36()) return true;
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpression_178_79_52()
 {
    if (jj_scan_token(DIVIDE)) return true;
    if (jj_3R_UnaryExpression_181_7_44()) return true;
    return false;
  }

  static private boolean jj_3_7()
 {
    if (jj_scan_token(XINU)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_196_47_62()
 {
    if (jj_scan_token(NULL)) return true;
    return false;
  }

  static private boolean jj_3R_AndExpression_167_76_33()
 {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_EqualityExpression_169_5_32()) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_195_47_60()
 {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_3R_VarDeclaration_100_5_21()) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_3R_VarDeclaration_100_5_21()) return true;
    return false;
  }

  static private boolean jj_3R_OrExpression_166_70_31()
 {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_AndExpression_167_52_30()) return true;
    return false;
  }

  static private boolean jj_3R_VarDeclaration_100_28_23()
 {
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_Expression_165_47_25()) return true;
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_AndExpression_167_52_30()
 {
    if (jj_3R_EqualityExpression_169_5_32()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AndExpression_167_76_33()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_OrExpression_166_51_29()
 {
    if (jj_3R_AndExpression_167_52_30()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_OrExpression_166_70_31()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_PostfixExpression_188_25_71()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_Arguments_163_5_68()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_Expression_165_47_25()
 {
    if (jj_3R_OrExpression_166_51_29()) return true;
    return false;
  }

  static private boolean jj_3_8()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_201_9_70()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_3R_Expression_165_47_25()) return true;
    if (jj_scan_token(RBRACKET)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_8()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_BaseType_108_7_28()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_AdditiveExpression_175_35_41()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_AdditiveExpression_175_35_46()) {
    jj_scanpos = xsp;
    if (jj_3R_AdditiveExpression_175_97_47()) return true;
    }
    return false;
  }

  static private boolean jj_3R_AdditiveExpression_175_35_46()
 {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_MultiplicativeExpression_178_5_40()) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_200_9_69()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_107_7_27()
 {
    if (jj_scan_token(INT_TYPE)) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_106_7_26()
 {
    if (jj_scan_token(BOOLEAN)) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_106_7_24()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_BaseType_106_7_26()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseType_107_7_27()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseType_108_7_28()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_199_7_65()
 {
    if (jj_scan_token(NEW)) return true;
    if (jj_3R_Type_103_5_22()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PrimaryExpression_200_9_69()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_201_9_70()) return true;
    }
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_198_7_64()
 {
    if (jj_scan_token(XINU)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_Arguments_163_5_68()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_197_7_63()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_Expression_165_47_25()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpression_178_26_51()
 {
    if (jj_scan_token(TIMES)) return true;
    if (jj_3R_UnaryExpression_181_7_44()) return true;
    return false;
  }

  static private boolean jj_3R_MultiplicativeExpression_178_26_45()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_MultiplicativeExpression_178_26_51()) {
    jj_scanpos = xsp;
    if (jj_3R_MultiplicativeExpression_178_79_52()) return true;
    }
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_196_7_61()
 {
    if (jj_scan_token(THIS)) return true;
    return false;
  }

  static private boolean jj_3R_Type_103_5_22()
 {
    if (jj_3R_BaseType_106_7_24()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_4()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_195_7_59()
 {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_194_7_58()
 {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  static private boolean jj_3R_RelationalExpression_172_29_37()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_RelationalExpression_172_29_42()) {
    jj_scanpos = xsp;
    if (jj_3R_RelationalExpression_172_88_43()) return true;
    }
    return false;
  }

  static private boolean jj_3R_RelationalExpression_172_29_42()
 {
    if (jj_scan_token(LT)) return true;
    if (jj_3R_AdditiveExpression_175_5_36()) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_193_7_57()
 {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  static private boolean jj_3R_VarDeclaration_100_5_21()
 {
    if (jj_3R_Type_103_5_22()) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_VarDeclaration_100_28_23()) jj_scanpos = xsp;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_scan_token(PUBLIC)) return true;
    return false;
  }

  static private boolean jj_3R_EqualityExpression_169_31_35()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_EqualityExpression_169_31_38()) {
    jj_scanpos = xsp;
    if (jj_3R_EqualityExpression_169_92_39()) return true;
    }
    return false;
  }

  static private boolean jj_3R_EqualityExpression_169_31_38()
 {
    if (jj_scan_token(EQ)) return true;
    if (jj_3R_RelationalExpression_172_5_34()) return true;
    return false;
  }

  static private boolean jj_3R_Arguments_163_36_74()
 {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_Expression_165_47_25()) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_192_7_56()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_192_7_54()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PrimaryExpression_192_7_56()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_193_7_57()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_194_7_58()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_195_7_59()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_195_47_60()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_196_7_61()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_196_47_62()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_197_7_63()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_198_7_64()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_199_7_65()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_scan_token(PUBLIC)) return true;
    if (jj_scan_token(VOID)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpression_188_7_67()
 {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PostfixExpression_188_25_71()) {
    jj_scanpos = xsp;
    if (jj_3R_PostfixExpression_188_97_72()) return true;
    }
    return false;
  }

  static private boolean jj_3R_PostfixExpression_187_7_66()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_3R_Expression_165_47_25()) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpression_187_7_55()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PostfixExpression_187_7_66()) {
    jj_scanpos = xsp;
    if (jj_3R_PostfixExpression_188_7_67()) return true;
    }
    return false;
  }

  static private boolean jj_3R_PostfixExpression_186_5_53()
 {
    if (jj_3R_PrimaryExpression_192_7_54()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_PostfixExpression_187_7_55()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_PostfixExpression_188_97_72()
 {
    return false;
  }

  static private boolean jj_3R_UnaryExpression_183_7_50()
 {
    if (jj_3R_PostfixExpression_186_5_53()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MiniJavaParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[35];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x400,0x7e820000,0x10000,0x40000,0x600800,0x600000,0x0,0x600000,0x80000,0x0,0x600000,0x7e820000,0x7e820000,0x2800000,0x7c020000,0x7e820000,0x1000000,0x0,0x7c020000,0x80000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x7c020000,0x0,0x0,0x0,0x0,0x7c020000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x705240,0x400000,0x0,0x400000,0x400000,0x400,0x400000,0x0,0x80000,0x400000,0x705240,0x705240,0x1000,0x704240,0x705240,0x0,0x80000,0x704240,0x0,0x1,0x6,0x6,0x18,0x18,0x60,0x60,0x180,0x180,0x704240,0x10800,0x4000,0x10800,0x14000,0x704000,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[8];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniJavaParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniJavaParser(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 35; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 35; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniJavaParser(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 35; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 35; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniJavaParser(MiniJavaParserTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 35; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniJavaParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 35; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[58];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 35; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 58; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 8; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

                              }
